### ISSUE TITLE
RND on git

### ISSUE THREAD

**Issue by almabud** [farjanahossainsimona/ecom_core#4]
RND on git. Know and learn more about git and how to use it. 

> You must create a `forlder` in your google drive and inside the folder create a doc named `git_learning`. In this doc you should write your learning as a cheatsheet. For example, you can follow mine. [sample_learning_cheatsheet_doc](https://docs.google.com/document/d/139miJVWRTzNwVVmMFce1ljCIqrEzRiW_VUwWZdEGXNI/edit?usp=share_link)

> Basically you need to learn the git basic commands. eg. `pull`, `push`, `commit`, `checkout`, `checkout -d` etc.

**Comment by farjana-hossain** [comment]
RND on git: [git learning](https://docs.google.com/document/d/1Xfzhf34tuo9sJafzJlgKJNaWO_TevyZXiAHEiX8nR94/edit?usp=share_link)

**Comment by almabud** [comment]
Good work 👍 .
